"use client";

import { Product } from "./columns";
import {
  MdBuild,
  MdPhoneIphone,
  MdChair,
  MdBook,
  MdChildCare,
  MdStar,
  MdHomeRepairService,
  MdFitnessCenter,
  MdKitchen,
} from "react-icons/md";

export const products: Product[] = [
  {
    id: "1",
    name: "Chave de Fenda",
    supplier: "TollSupplier Inc.",
    sku: "SD123",
    category: "Outros",
    status: "Rascunho",
    quantityInStock: 50,
    price: 12.99,
    icon: MdBuild,
  },
  {
    id: "2",
    name: "Smartphone",
    supplier: "TechGiant Corp.",
    sku: "SP456",
    category: "Eletrônicos",
    status: "Publicado",
    quantityInStock: 120,
    price: 499.99,
    icon: MdPhoneIphone,
  },
  {
    id: "3",
    name: "Cadeira de Escritório",
    supplier: "ComfortFurniture",
    sku: "CH789",
    category: "Mobiliário",
    status: "Publicado",
    quantityInStock: 30,
    price: 99.99,
    icon: MdChair,
  },
  {
    id: "4",
    name: "Supote para Notebook",
    supplier: "ErgoGoods",
    sku: "LS234",
    category: "Eletrônicos",
    status: "Inativo",
    quantityInStock: 15,
    price: 35.5,
    icon: MdBuild,
  },
  {
    id: "5",
    name: "Livro de JavaScript",
    supplier: "BookWorld",
    sku: "JB567",
    category: "Livros",
    status: "Publicado",
    quantityInStock: 60,
    price: 29.99,
    icon: MdBook,
  },
  {
    id: "6",
    name: "Ursinho de Pelúcia",
    supplier: "ToyFactory",
    sku: "TB890",
    category: "Brinquedos",
    status: "Publicado",
    quantityInStock: 200,
    price: 14.99,
    icon: MdChildCare,
  },
  {
    id: "7",
    name: "Creme Facial",
    supplier: "BeautyCo",
    sku: "FC123",
    category: "Beleza",
    status: "Publicado",
    quantityInStock: 100,
    price: 25.99,
    icon: MdStar,
  },
  {
    id: "8",
    name: "Colchonete de Yoga",
    supplier: "FitnessPro",
    sku: "YM456",
    category: "Esportes",
    status: "Publicado",
    quantityInStock: 80,
    price: 19.99,
    icon: MdFitnessCenter,
  },
  {
    id: "9",
    name: "Cafeteira",
    supplier: "HomeTech",
    sku: "CM789",
    category: "Eletrodomésticos",
    status: "Publicado",
    quantityInStock: 45,
    price: 89.99,
    icon: MdHomeRepairService,
  },
  {
    id: "10",
    name: "Sofá",
    supplier: "CozyLiving",
    sku: "CO112",
    category: "Mobiliário",
    status: "Inativo",
    quantityInStock: 20,
    price: 299.99,
    icon: MdChair,
  },
  {
    id: "11",
    name: "Liquidificador",
    supplier: "KitchenEssentials",
    sku: "BL345",
    category: "Eletrodomésticos",
    status: "Publicado",
    quantityInStock: 60,
    price: 49.99,
    icon: MdKitchen,
  },
  {
    id: "12",
    name: "Tênis de Corrida",
    supplier: "SportMaster",
    sku: "RS678",
    category: "Esportes",
    status: "Publicado",
    quantityInStock: 150,
    price: 59.99,
    icon: MdFitnessCenter,
  },
  {
    id: "13",
    name: "Relógio de Parede",
    supplier: "HomeDesigns",
    sku: "WC901",
    category: "Decoração",
    status: "Publicado",
    quantityInStock: 75,
    price: 34.99,
    icon: MdBuild,
  },
  {
    id: "14",
    name: "Luminária de Leitura",
    supplier: "LightWorks",
    sku: "RL234",
    category: "Decoração",
    status: "Rascunho",
    quantityInStock: 40,
    price: 45.99,
    icon: MdBuild,
  },
  {
    id: "15",
    name: "Purificador de Ar",
    supplier: "CleanAir Solutions",
    sku: "AP567",
    category: "Eletrodomésticos",
    status: "Publicado",
    quantityInStock: 25,
    price: 149.99,
    icon: MdHomeRepairService,
  },
];
